import Head from "next/head";

import { API_URL } from "@/config/index";

import Layout from "@/components/Layout";
import FilmItem from "@/components/FilmItem";

import styles from "@/styles/Home.module.scss";

export const getStaticProps = async () => {
  const res = await fetch(`${API_URL}/films`);
  const films = await res.json();

  return { props: { films: films.slice(0, 3) }, revalidate: 1 };
};

export default function Home({ films }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <h1>Films</h1>
        <div className={styles.filmsContainer}>
          {films.length === 0 && <div>No Films to show...</div>}
          {films.map((film) => {
            return <FilmItem key={film.id} id={film.id} films={films} />;
          })}
        </div>
      </Layout>
    </div>
  );
}
