import Head from "next/head";
import Image from "next/image";

import Layout from "../components/Layout";

import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <h1>Films</h1>
        <Image
          className={styles.filmImg1}
          src={
            "https://images.unsplash.com/photo-1610030181087-540017dc9d61?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2832&q=80"
          }
          width={600}
          height={360}
          alt='image'
        />
      </Layout>
    </div>
  );
}
